//Measurement
###
POST http://localhost:8080/measurement
Content-Type: application/json

{
  "name": "kg",
  "active": true
}

###
PUT http://localhost:8080/measurement/2
Content-Type: application/json

{
  "name": "santimetr",
  "active": true
}


###
GET http://localhost:8080/measurement?page=1

###
GET http://localhost:8080/measurement/1


//Category
###
POST http://localhost:8080/categpry
Content-Type: application/json

{
  "name": "Chexollar",
  "active": true,
  "parentId": 1
}

###
PUT http://localhost:8080/categpry/3
Content-Type: application/json

{
  "name": "Telefon Chexollar",
  "active": true,
  "parentId": 1
}

###
GET http://localhost:8080/categpry?page=0

###
GET http://localhost:8080/categpry/1


//Valyuta kurslari
###
GET http://localhost:8080/currency?page=0

<> 2021-03-10T140357.200.json

###
POST http://localhost:8080/currency
Content-Type: application/json

{
  "name": "USD",
  "active": true
}

###
PUT http://localhost:8080/currency/2
Content-Type: application/json

{
  "name": "EUR",
  "active": true
}

###
GET http://localhost:8080/currency/2

//Supplier
###
POST http://localhost:8080/supplier
Content-Type: application/json

{
  "phoneNumber": "998954444444",
  "name": "Otash Otashov",
  "active" : true
}

###
PUT http://localhost:8080/supplier/2
Content-Type: application/json

{
  "phoneNumber": "998954444444",
  "name": "Otash Olimov",
  "active" : false
}

###
GET http://localhost:8080/supplier?page=0

###
GET http://localhost:8080/supplier/1


//WareHouse
###
POST http://localhost:8080/warehouse
Content-Type: application/json

{
  "name": "A95",
  "active" : true
}

###
PUT http://localhost:8080/warehouse/1
Content-Type: application/json

{
  "name": "B65",
  "active" : true
}

###
GET http://localhost:8080/warehouse?page=0

###
GET http://localhost:8080/warehouse/1

//User
###
POST http://localhost:8080/user
Content-Type: application/json

{
  "firstName": "Hayot",
  "lastName": "Raximov",
  "phoneNumber": "998954446688",
  "password": "root123",
  "wareHouseId": [1],
  "status": true
}

###
PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "firstName": "Hayot",
  "lastName": "Raximov",
  "phoneNumber": "998954446688",
  "password": "root123",
  "wareHouseId": [1,2],
  "status": true
}

###
GET http://localhost:8080/user?page=0

###
GET http://localhost:8080/user/1


//Client uchun

###
POST http://localhost:8080/client
Content-Type: application/json

{
  "name": "Jalil Jalilov",
  "phoneNumber": "998785452544"
}

###
PUT http://localhost:8080/client/1
Content-Type: application/json

{
  "name": "Jalil Olimov",
  "phoneNumber": "998785452544"
}

###
GET http://localhost:8080/client?page=0

###
GET http://localhost:8080/client/1

//Product
###
POST http://localhost:8080/product
Content-Type: application/json

{
  "name": "Samsung A10",
  "categoryId": 1,
  "measurementId": 1,
  "attachmentId": 1,
  "active": true
}

<> 2021-03-10T165541.200.json

###
PUT http://localhost:8080/product/1
Content-Type: application/json

{
  "name": "Samsung A10",
  "categoryId": 1,
  "measurementId": 3,
  "attachmentId": 1,
  "active": true
}


###
GET http://localhost:8080/product?page=0

###
GET http://localhost:8080/product/1


//Input uchun
###
POST http://localhost:8080/input
Content-Type:application/json

{
  "warehouseId": 1,
  "supplierId": 1,
  "currencyId": 1,
  "facturNumber": 255,
  "date": "2021-01-01"
}

###
PUT http://localhost:8080/input/1
Content-Type:application/json

{
  "warehouseId": 1,
  "supplierId": 1,
  "currencyId": 1,
  "facturNumber": 255,
  "date": "2021-02-01"
}

###
GET http://localhost:8080/input?page=0

###
GET http://localhost:8080/input/1


//Input Product uchun
###
POST http://localhost:8080/inputproduct
Content-Type: application/json

{
  "productId": 1,
  "amount": 50,
  "price": 541,
  "date": "2021-03-20",
  "inputId": 1
}

###
PUT http://localhost:8080/inputproduct/1
Content-Type: application/json

{
  "productId": 1,
  "amount": 50,
  "price": 541,
  "date": "2022-03-20",
  "inputId": 1
}

###
GET http://localhost:8080/inputproduct?page=0

###
GET http://localhost:8080/inputproduct/1

//Output

###
POST http://localhost:8080/output
Content-Type: application/json

{
  "warehouseId": 2,
  "clientId": 1,
  "currencyId": 2,
  "facturNumber": 12,
  "date": "2021-03-10"
}

###
PUT http://localhost:8080/output/1
Content-Type: application/json

{
  "warehouseId": 2,
  "clientId": 1,
  "currencyId": 2,
  "facturNumber": 12,
  "date": "2011-03-10"
}

###
GET http://localhost:8080/output?page=0

###
GET http://localhost:8080/output/1

//Output product uchun
###
POST http://localhost:8080/outputproduct
Content-Type: application/json

{
  "productId": 1,
  "amount": 54,
  "price": 200,
  "outputId": 1
}

###
PUT http://localhost:8080/outputproduct/2
Content-Type: application/json

{
  "productId": 1,
  "amount": 54,
  "price": 450,
  "outputId": 1
}

###
GET http://localhost:8080/outputproduct?page=0

###
GET http://localhost:8080/outputproduct/1

